[package]
name = "test_no_std"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libc = { version = "0.2", default-features = false }
partially = { version = "*", path = "../partially", default-features = false, features = [
    "derive",
] }
