name: PR validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-all-features
        run: cargo install cargo-all-features
      - name: Build
        run: cargo build-all-features --verbose
      - name: Run tests
        run: cargo test-all-features --verbose
      - name: Run clippy
        run: cargo clippy --verbose
